# Generated by Django 4.2.7 on 2025-10-14 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPIntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên cấu hình ERP')),
                ('erp_type', models.CharField(choices=[('SAP', 'SAP'), ('Odoo', 'Odoo'), ('QuickBooks', 'QuickBooks'), ('Custom', 'Hệ thống tùy chỉnh')], default='Custom', max_length=50, verbose_name='Loại ERP')),
                ('api_endpoint', models.URLField(verbose_name='Endpoint API ERP')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='Ánh xạ trường (OCR -> ERP)')),
                ('auto_post_on_match', models.BooleanField(default=False, verbose_name='Tự động tích hợp khi khớp')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoices/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Đã tải lên'), ('OCR_PROCESSING', 'Đang xử lý OCR'), ('OCR_PROCESSED', 'Đã xử lý OCR'), ('PENDING_REVIEW', 'Chờ xem xét'), ('MATCH_PROCESSING', 'Đang đối chiếu'), ('MATCHED', 'Đã khớp'), ('UNMATCHED', 'Chưa khớp'), ('PENDING_APPROVAL', 'Chờ phê duyệt'), ('APPROVED', 'Đã phê duyệt'), ('INTEGRATING', 'Đang tích hợp ERP'), ('INTEGRATED', 'Đã tích hợp ERP'), ('INTEGRATION_ERROR', 'Lỗi tích hợp ERP'), ('REJECTED', 'Đã từ chối')], default='UPLOADED', max_length=50)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_name_ocr', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('matched_erp_record_id', models.CharField(blank=True, max_length=255, null=True)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discrepancy_details', models.JSONField(blank=True, null=True)),
                ('ocr_start_time', models.DateTimeField(blank=True, null=True)),
                ('ocr_end_time', models.DateTimeField(blank=True, null=True)),
                ('match_start_time', models.DateTimeField(blank=True, null=True)),
                ('match_end_time', models.DateTimeField(blank=True, null=True)),
                ('integration_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('OCR_REVIEW', 'Review OCR'), ('MATCH_REVIEW', 'Review Match'), ('APPROVAL', 'Approval')], max_length=50, verbose_name='Loại nhiệm vụ')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('IN_PROGRESS', 'Đang thực hiện'), ('COMPLETED', 'Hoàn thành'), ('CANCELED', 'Đã hủy')], default='PENDING', max_length=50, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app_invoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên quy tắc')),
                ('rule_definition', models.JSONField(verbose_name='Định nghĩa quy tắc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('priority', models.IntegerField(default=1, verbose_name='Độ ưu tiên')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_rules', to='app_invoices.erpintegrationconfig')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_invoices.supplier'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('extracted_value', models.TextField()),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('corrected_value', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='app_invoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_invoices.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
