# Generated by Django 4.2.7 on 2025-10-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
