# Generated by Django 4.2.7 on 2025-10-15 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_invoices', '0002_invoice_ocr_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='ocr_text',
            new_name='raw_ocr_text',
        ),
        migrations.RemoveField(
            model_name='erpintegrationconfig',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='erpintegrationconfig',
            name='field_mapping',
        ),
        migrations.RemoveField(
            model_name='extractedfield',
            name='bounding_box',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discrepancy_details',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='integration_time',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='match_end_time',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='match_start_time',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='matched_erp_record_id',
        ),
        migrations.RemoveField(
            model_name='matchingrule',
            name='rule_definition',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='notes',
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matchingrule',
            name='rule_logic',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='invoice',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                to='app_invoices.invoice',
                # DÒNG SỬA LỖI IntegrityError: cho phép NULL tạm thời
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='erpintegrationconfig',
            name='api_endpoint',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='erpintegrationconfig',
            name='auto_post_on_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='erpintegrationconfig',
            name='erp_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='erpintegrationconfig',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='extractedfield',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(upload_to='invoices/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='match_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Đã tải lên'), ('processing', 'Đang xử lý OCR'), ('ocr_processed', 'Đã xử lý OCR'), ('matched', 'Đã khớp'), ('mismatch', 'Sai lệch'), ('awaiting_approval', 'Chờ phê duyệt'), ('integration_error', 'Lỗi tích hợp ERP'), ('rejected', 'Bị từ chối')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchingrule',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_invoices.erpintegrationconfig'),
        ),
        migrations.AlterField(
            model_name='matchingrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matchingrule',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matchingrule',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='task_type',
            field=models.CharField(max_length=50),
        ),
    ]