# Generated by Django 4.2.7 on 2025-10-16 10:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_invoices', '0003_rename_ocr_text_invoice_raw_ocr_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpintegrationconfig',
            name='api_endpoint',
        ),
        migrations.RemoveField(
            model_name='erpintegrationconfig',
            name='auto_post_on_match',
        ),
        migrations.RemoveField(
            model_name='erpintegrationconfig',
            name='erp_type',
        ),
        migrations.RemoveField(
            model_name='erpintegrationconfig',
            name='name',
        ),
        migrations.RemoveField(
            model_name='extractedfield',
            name='corrected_value',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='supplier_name_ocr',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='matchingrule',
            name='integration',
        ),
        migrations.RemoveField(
            model_name='matchingrule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='erpintegrationconfig',
            name='api_key',
            field=models.CharField(default='default_api_key', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='erpintegrationconfig',
            name='api_url',
            field=models.URLField(default='https://default-api-url.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='erpintegrationconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='erpintegrationconfig',
            name='system_name',
            field=models.CharField(default='Default ERP System', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extractedfield',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='app_invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='match_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='raw_ocr_text',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Đã tải lên'), ('OCR_PROCESSING', 'Đang xử lý OCR'), ('OCR_PROCESSED', 'Đã xử lý OCR'), ('PENDING_REVIEW', 'Chờ xem xét'), ('MATCHED', 'Đã khớp'), ('UNMATCHED', 'Sai lệch'), ('PENDING_APPROVAL', 'Chờ phê duyệt'), ('INTEGRATION_ERROR', 'Lỗi tích hợp ERP'), ('REJECTED', 'Bị từ chối'), ('APPROVED', 'Đã phê duyệt')], default='UPLOADED', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchingrule',
            name='priority',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 16, 10, 13, 42, 62218, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
