# Generated by Django 4.2.7 on 2025-10-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoices', '0004_remove_erpintegrationconfig_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
