# Generated by Django 4.2.7 on 2025-10-17 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_invoices', '0005_invoice_is_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('classifier', 'Phân loại'), ('extractor', 'Trích xuất'), ('fraud_detector', 'Phát hiện fraud'), ('predictor', 'Dự đoán')], max_length=50)),
                ('training_data_count', models.IntegerField(default=0)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model_file_path', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='ai_category',
            field=models.CharField(blank=True, help_text='Phân loại AI', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Độ tin cậy AI', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ai_extracted_data',
            field=models.JSONField(blank=True, help_text='Dữ liệu AI trích xuất', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ai_processing_time',
            field=models.IntegerField(blank=True, help_text='Thời gian xử lý AI (giây)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ai_recommendations',
            field=models.TextField(blank=True, help_text='Khuyến nghị AI'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fraud_risk_level',
            field=models.CharField(blank=True, help_text='Mức độ rủi ro', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fraud_risk_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Điểm rủi ro fraud', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('approval', 'Phê duyệt'), ('review', 'Xem xét'), ('reject', 'Từ chối'), ('manual_check', 'Kiểm tra thủ công')], max_length=50)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField()),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_invoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Người dùng'), ('ai', 'AI Bot'), ('system', 'Hệ thống')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('context', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_invoices.aichatsession')),
            ],
        ),
    ]
